version: '3.1'
services:
    zswblogcore:
      image: registry.cn-hangzhou.aliyuncs.com/zswblogcore/zswblogcore:latest-5
      container_name: zswblog
      environment:
        - ASPNETCORE_URLS="http://+:8004"
        - ASPNETCORE_ENVIRONMENT=Product
        - CONNECTIONSTRINGS_REDISCONNECTIONSTRING="182.61.148.221:6379,password=732668,database=0"
        - CONNECTIONSTRINGS_CLUSTERMYSQLCONNECTION="server=182.61.148.221;port=3306;database=zswblog;SslMode=None;uid=root;pwd=732668;Allow User Variables=true;"
        - CONNECTIONSTRINGS_MASTERMYSQLCONNECTION="server=182.61.148.221;port=3306;database=zswblog;SslMode=None;uid=root;pwd=732668;Allow User Variables=true;"
        - QQAPPKEY=101858486
        - QQAPPSECRET=9ae0e34cadf786a0a7050659423a55e8
        - LOCATIONKEY=HIQBZ-WNQKK-6VZJ7-AR3XK-HEVAK-5DBXD
        - EMAILSENDADDRESS="1761317983@qq.com"
        - EMAILSECRETKEY=emqwtiqpmrpccbae
        - MUSICBASESITE="/PLAYLIST/DETAIL?ID=585511463"            
        - ACCESSKEYID=LTAI4GDdBoYhq6z8MHd9cxim
        - ACCESSKEYSECRET=31p2Z0XTVFvhrhl1e1JhzqAV5lYBL4
        - ENDPOINT="oss-cn-hangzhou.aliyuncs.com"
        - BUCKETNAME=zswblog
      ports:
        - "8004:8004"
      volumes:
        - ./data/app/config:/app/config