version: '3.1'
services:
    zswblogcore:
      image: registry.cn-hangzhou.aliyuncs.com/zswblogcore/zswblogcore:latest-20
      container_name: zswblog
      environment:
        - ASPNETCORE_URLS=http://+:8004
        - ASPNETCORE_ENVIRONMENT=Production
        # Redis和Mysql主从连接地址配置
        - CONNECTIONSTRINGS__REDISCONNECTIONSTRING=
        - CONNECTIONSTRINGS__CLUSTERMYSQLCONNECTION=
        - CONNECTIONSTRINGS__MASTERMYSQLCONNECTION=
        # QQ登录AppKey和Secret
        - QQAPPKEY=
        - QQAPPSECRET=
        # 腾讯位置开发者AppSecret
        - LOCATIONKEY=
        # 邮箱服务回访地址,发送邮箱配置和smtp key
        - ENV EMAILRETURNBACKURL=
        - EMAILSENDADDRESS=
        - EMAILSECRETKEY=
        # 网易云音乐站服务器地址和歌单id
        - MUSICBASEURL=
        - MUSICBASESITE=/PLAYLIST/DETAIL?ID=
        # 阿里云OSS地址
        - ACCESSKEYID=
        - ACCESSKEYSECRET=
        - ENDPOINT=
        - BUCKETNAME=
      ports:
        - "8004:8004"
      volumes:
        - ./data/app/config:/app/config
